---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.branch }}-pgval"
  annotations:
    deployment.kubernetes.io/revision: {{ .Release.Revision }}
    deployment.git-branch: {{ .Values.branch }}
type: Opaque
stringData:
  DB_USER: {{ .Values.postgresql.global.postgresql.auth.username }}
  DB_PASSWORD: {{ .Values.postgresql.global.postgresql.auth.password}}
  DB_DATABASE: {{ .Values.postgresql.global.postgresql.auth.database}}
  DB_HOST: {{ .Chart.Name }}-postgresql
  DB_PORT: {{ .Values.postgresql.global.postgresql.service.port.postgresql }}