---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.branch }}-svc"
  labels:
    app: "{{ .Chart.Name }}-{{ .Values.branch }}"
  annotations:
    deployment.kubernetes.io/revision: "{{ .Release.Revision }}"
    deployment.git-branch: "{{ .Values.branch }}"
spec:
  ports:
    {{- range $port := .Values.ports }}
    - name: {{ $port.name }}
      port: {{ $port.containerPort }}
      targetPort: {{ $port.containerPort }}
      protocol: {{ $port.protocol }}
    {{- end }}
  selector:
    app: "{{ .Chart.Name }}-{{ .Values.branch }}"
  type: ClusterIP