[package]
name = "api"
version = "0.1.0"
edition = "2021"
authors = ["Batleforc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-cors = "0.6"
utoipa = {version="3",features= ["actix_extras","chrono","uuid"] }
utoipa-swagger-ui = { version = "3", features = ["actix-web"] }
uuid = { version = "1.2.2", features = ["v4","serde"]}
bcrypt = "0.14.0"
serde = "1.0.152"
dotenvy = "0.15.6"
tracing = "0.1.37"
tracing-actix-web = { version = "0.7.2", features = ["opentelemetry_0_18"]}
opentelemetry = { version = "0.18", features = ["rt-tokio-current-thread"] }
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
opentelemetry-jaeger = { version = "0.17.0" , features = ["rt-tokio-current-thread"]}
tracing-bunyan-formatter = "0.3.6"
tracing-opentelemetry = "0.18.0"
actix-web-prom = "0.6.0"
serde_json = "1.0"
chrono = { version = "0.4.23", features = ["serde"] }
tokio-postgres = { version = "0.7.7", features = ["with-uuid-1","with-chrono-0_4","with-serde_json-1"] }
deadpool-postgres = { version = "0.10", features = ["serde"]}
jsonwebtoken = "8.2.0"
regex = "1.7.1"
openssl = { version = "0.10"}
postgres-openssl = "0.5.0"
totp-rs = {version = "4.2.0", features = ["serde_support","qr","gen_secret"]}
