from_latest_tag = false
ignore_merge_commits = false
generate_mono_repository_global_tag = true
branch_whitelist = []
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
cargo fmt -v --all --check
"""

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "batleforc"
repository = "rust-template"
authors = [
  { signature = "Maxime Leriche", username = "batleforc" },
]

[bump_profiles]

[packages]
