services:
  db-test:
    image: postgres:15
    environment:
      POSTGRES_USER: GB8eE8vh
      POSTGRES_PASSWORD: 1OLlRZo1tnNluvx
      POSTGRES_DB: 1pNkVsX3FgFeiQdga
    ports:
      - 5433:5432
  sonarscanner:
    container_name: sonarscanner
    image: harbor.weebo.fr/cache/sonarsource/sonar-scanner-cli:5
    volumes:
      - ./:/usr/src
    command:
      - -X
