postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: rust-user
        password: "exMLfCMzbHkiH"
        database: rust
      service:
        port:
          postgresql: 5432
  primary:
    persistence:
      enabled: true
      size: "2Gi"

branch: main

image:
  repository: harbor.weebo.fr/template/template-rust
  pullPolicy: Always
  tag: "v1.17.8" # En dev a remplacer par la branch git

ports:
  - name: http
    containerPort: 8080
    protocol: TCP

probe:
  liveness:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10

env:
  - name: PORT
    value: "8080"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://tempo.monitoring.svc.cluster.local:4318"
  - name: AUTH_TYPE
    value: OIDC
  - name: RUST_LOG
    value: "trace"

resources: # Need to be fine tunned in the futur
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 20m
    memory: 16Mi

ingress:
  - host: template.weebo.fr
    secretName: template-weebo-fr
    path: /api
    pathType: Prefix
    port: 8080

auth:
  override: false
  issuer: https://login.weebo.fr
  scopes: "openid profile email offline_access"
