apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: {{.Values.config.prefix}}-pipeline-template
spec:
  params:
    - name: gitrevision
      description: The git revision (SHA)
      default: master
    - name: gitbranch
      description: The git branch
      default: master
    - name: gitrepositoryurl
      description: The git repository url ("https://github.com/batleforc/rust-template")
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: {{.Values.config.prefix}}-pipeline-run-
      spec:
        pipelineRef:
          name: {{.Values.config.prefix}}-pipeline
        workspaces:
          - name: shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: dockerconfig
            secret:
              secretName: harbor-auth
          - name: kubeconfig
            secret:
              secretName: name: kubeconfig
        params:
          - name: repo-revision
            value: $(tt.params.gitrevision)
          - name: repo-branch
            value: $(tt.params.gitbranch)
          - name: repo-url
            value: $(tt.params.gitrepositoryurl)
