config:
  prefix: tpl-rust
  name: batleforc
  ingress:
    class: haproxy
    domain: webhook.weebo.fr
  registry:
    imageName: template/template-rust
  sonarqube:
    enabled: true
    host: https://qube.weebo.fr
    image: harbor.weebo.fr/sonar/rust:v1.17.12
    useToken: true
    additionalScript:
      enabled: true
      image: harbor.weebo.fr/sonar/rust:v1.17.12-prepare
      script: |
        set -x
        cargo clippy --message-format=json > clippy-report.json
        cargo audit --json > audit-report.json
        cargo outdated --depth 1 --format json > outdated-report.json
        cargo sonar --issues clippy,audit,outdated --clippy-path clippy-report.json --audit-path audit-report.json --outdated-path outdated-report.json
