config:
  prefix: tpl-rust
  name: batleforc
  ingress:
    class: haproxy
    domain: webhook.weebo.fr
  registry:
    imageName: template/template-rust
  sonarqube:
    enabled: true
    host: qube.weebo.fr
    image: harbor.weebo.fr/sonar/rust:v1.17.3
    useToken: true
    additionalScript: |
      set -ex
      cargo clippy
