config:
  prefix: tpl-rust
  name: batleforc
  ingress:
    class: haproxy
    domain: webhook.weebo.fr
  registry:
    imageName: template/template-rust
  sonarqube:
    enabled: true
    host: qube.weebo.fr
    image: harbor.weebo.fr/sonar/rust:v1.17.1
    useToken: true
    additionalScript:
      - cargo clippy --message-format=json &> clippy-report.json
