apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: batleforc-template-rust
  name: batleforc-template-rust
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: batleforc-template-rust
  name: batleforc-template-rust
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: batleforc-template-rust
  namespace: batleforc-template-rust
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: batleforc-template-rust
subjects:
  - kind: ServiceAccount
    name: batleforc-template-rust
    namespace: batleforc-template-rust
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: batleforc-template-rust
  name: batleforc-template-rust-binding-2
subjects:
  - kind: ServiceAccount
    name: batleforc-template-rust
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: batleforc-template-rust-clusterbinding
subjects:
  - kind: ServiceAccount
    name: batleforc-template-rust
    namespace: batleforc-template-rust
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
---
apiVersion: v1
kind: Secret
metadata:
  name: batleforc-template-rust
  namespace: batleforc-template-rust
  annotations:
    kubernetes.io/service-account.name: batleforc-template-rust
type: kubernetes.io/service-account-token
